apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: http-svc
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
