apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: haproxy-ingress
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
